/*=============================================================================
   WARNING!!  This file is overwritten by the UIStyler each time the Styler 
   file is saved.
  
  
        Filename:  opu_cam6_dlg.h
  
        This file was generated by the NX User Interface Styler
        Created by: ChudoyakovEB68
        Version: NX 4
              Date: 11-06- 7
              Time: 19:58
  
   This include file is overwritten each time the UIStyler dialog is
   saved.  Any modifications to this file will be lost.
==============================================================================*/
 
 
#ifndef OPU_CAM6_DLG_H_INCLUDED
#define OPU_CAM6_DLG_H_INCLUDED
 
#include <uf.h> 
#include <uf_defs.h>
#include <uf_styler.h> 


#ifdef __cplusplus
extern "C" {
#endif


/*------------------ UIStyler Dialog Definitions  ------------------- */
/* The following values are definitions into your UIStyler dialog.    */
/* These values will allow you to modify existing objects within your */
/* dialog.   They work directly with the NX Open API,                 */
/* UF_STYLER_ask_value, UF_STYLER_ask_values, and UF_STYLER_set_value.*/
/*------------------------------------------------------------------- */
 
#define PR_TAB_CTRL_BEG_0              ("TAB_CTRL_BEG_0")
#define PR_PAGE_BEG_1                  ("PAGE_BEG_1")
#define PR_GR_BEG_2                    ("GR_BEG_2")
#define PR_LABEL_3                     ("LABEL_3")
#define PR_LABEL_4                     ("LABEL_4")
#define PR_LABEL_5                     ("LABEL_5")
#define PR_LABEL_6                     ("LABEL_6")
#define PR_LABEL_7                     ("LABEL_7")
#define PR_GR_END_3                    ("GR_END_3")
#define PR_SEP_9                       ("SEP_9")
#define PR_OPTION_MACH                 ("OPTION_MACH")
#define PR_SEP_11                      ("SEP_11")
#define PR_LABEL_12                    ("LABEL_12")
#define PR_TOGGLE_OPERZOFFSET          ("TOGGLE_OPERZOFFSET")
#define PR_REAL_OPERZOFFSET            ("REAL_OPERZOFFSET")
#define PR_SEP_15                      ("SEP_15")
#define PR_LABEL_16                    ("LABEL_16")
#define PR_TOGGLE_XOFFSET              ("TOGGLE_XOFFSET")
#define PR_REAL_TOOLXOFFSET            ("REAL_TOOLXOFFSET")
#define PR_TOGGLE_YZOFFSET             ("TOGGLE_YZOFFSET")
#define PR_REAL_TOOLYOFFSET            ("REAL_TOOLYOFFSET")
#define PR_TOGGLE_ZOFFSET              ("TOGGLE_ZOFFSET")
#define PR_REAL_TOOLZOFFSET            ("REAL_TOOLZOFFSET")
#define PR_SEP_23                      ("SEP_23")
#define PR_TOGGLE_ORIGIN               ("TOGGLE_ORIGIN")
#define PR_REAL_ORIGINX                ("REAL_ORIGINX")
#define PR_REAL_ORIGINY                ("REAL_ORIGINY")
#define PR_REAL_ORIGINZ                ("REAL_ORIGINZ")
#define PR_SEP_28                      ("SEP_28")
#define PR_PAGE_END_2                  ("PAGE_END_2")
#define PR_PAGE_BEG_2                  ("PAGE_BEG_2")
#define PR_GR_BEG_31                   ("GR_BEG_31")
#define PR_LABEL_32                    ("LABEL_32")
#define PR_LABEL_33                    ("LABEL_33")
#define PR_LABEL_34                    ("LABEL_34")
#define PR_GR_END_32                   ("GR_END_32")
#define PR_SEP_35                      ("SEP_35")
#define PR_TOGGLE_DELZOFFSETOPER       ("TOGGLE_DELZOFFSETOPER")
#define PR_SEP_38                      ("SEP_38")
#define PR_TOGGLE_DELXOFFSETTOOL       ("TOGGLE_DELXOFFSETTOOL")
#define PR_TOGGLE_DELYZOFFSETTOOL      ("TOGGLE_DELYZOFFSETTOOL")
#define PR_TOGGLE_DELZOFFSETTOOL       ("TOGGLE_DELZOFFSETTOOL")
#define PR_SEP_42                      ("SEP_42")
#define PR_LABEL_43                    ("LABEL_43")
#define PR_TOGGLE_DELSTARTORIGIN       ("TOGGLE_DELSTARTORIGIN")
#define PR_SEP_45                      ("SEP_45")
#define PR_TOGGLE_DELSTARTUDEALL       ("TOGGLE_DELSTARTUDEALL")
#define PR_TOGGLE_DELENDUDEALL         ("TOGGLE_DELENDUDEALL")
#define PR_SEP_48                      ("SEP_48")
#define PR_PAGE_END_31                 ("PAGE_END_31")
#define PR_TAB_CTRL_END_3              ("TAB_CTRL_END_3")
#define PR_DIALOG_OBJECT_COUNT         ( 51 )
 

/*---------------- UIStyler Callback Prototypes --------------- */
/* The following function prototypes define the callbacks       */
/* specified in your UIStyler built dialog.  You are REQUIRED to*/
/* create the associated function for each prototype.  You must */
/* use the same function name and parameter list when creating  */
/* your callback function.                                      */
/*------------------------------------------------------------- */

int PR_construct_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_ok_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_apply_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_cancel_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_switch_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_mach_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_operzoffset_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_real_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_toolxoffset_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_toolyzoffset_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_toolzoffset_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_origin_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);

int PR_tog_cb ( int dialog_id,
             void * client_data,
             UF_STYLER_item_value_type_p_t callback_data);




#ifdef __cplusplus
}
#endif



#endif /* OPU_CAM6_DLG_H_INCLUDED */
